### ISSUE TITLE
Property "EditableColumn.question" is not defined. 

### ISSUE THREAD

**Issue by datguru** [vitalets/x-editable-yii#1]
Not 100% sure if this is an issue with this or not.

This is my Controller Code.

``` php
public function actionIndex()
    {

        $dataProvider=new CActiveDataProvider('Question');
        $this->render('index',array(
            'dataProvider'=>$dataProvider,
        ));
    }
```

This is my view Code

``` php
<?php $this->widget('bootstrap.widgets.TbGridView', array(
    'id' => 'question-grid',
    'itemsCssClass' => 'table-bordered',
    'dataProvider' => $dataProvider,
    'columns'=>array(
        array(
           'class' => 'editable.EditableColumn',
           'question' => 'question',
           'editable' => array(
                  'url'        => $this->createUrl('question/update'),
                  'placement'  => 'right',
              )               
        )
))); 
?>
```

My table structure is the following...

id | question | active | created | modified

Now I have used this exact same code on another controller and view and it works perfectly. However I seem to be getting the error Property "EditableColumn.question" is not defined. However I cannot see why it is not defined. As it is a valid value. However If I remove the columns part of the widget then it displays the table fine.

Apologies if this is not an issue with x-editable for Yii. I am not allowed to comment on the Yii extension comments section yet but its a fantastic plugin.

Thanks

Chris

**Comment by datguru** [comment]
Sorry I have been an idiot. In the columns part it needs to be name. Apologies closing this issue.

**Comment by vitalets** [comment]
never mind :)
