### ISSUE TITLE
Update X-editable from 1.4.6 to 1.5.1

### ISSUE THREAD

**Issue by Julian-B90** [vitalets/x-editable-yii#102]
Update the X-editable sources.

**Comment by Julian-B90** [comment]
and update the external sources

**Comment by gwelr** [comment]
Do you plan to merge  this branch into either dev or master anytime soon ?

**Comment by Julian-B90** [comment]
Still have a little test soon i will merge this in the dev branch

**Comment by chrisc0** [comment]
Any update on this issue?

**Comment by Julian-B90** [comment]
I have merged this issue now in the develop branch.
