### ISSUE TITLE
Conflict datepicker with JuiDatePicker

### ISSUE THREAD

**Issue by chameleon82** [vitalets/x-editable-yii#11]
X-editable DatePicker  периодически конфликтует с "zii.widgets.jui.CJuiDatePicker".

Я вставляю стандартный код виджета

``` php
  $this->widget('zii.widgets.jui.CJuiDatePicker',array( 'model' => $model
   ,'attribute' =>'begin_date'
   ,options = array ( .. ) 
);
```

но вместо него вижу x-editable DatePicker.
Полагаю, проблема где-то в JS,т.е. в bootstrap переписывается метод datepicker. Проблема скорее даже не в том, что виджет подменяется, а в том что options стандартного виджета не совпадает с options виджета bootstrap. Имхо, если datepicker должен переопределяться бутстрапом, это надо вынести в config, и привести все options к CJuiDatePicker, в противном случае - это баг.

**Comment by vitalets** [comment]
да, к cожалению оба datepicker'a используют одинаковый метод $().datepicker и конфликтуют на одной странице. В бутстраповском висит пул реквест с поддержкой noConflict https://github.com/eternicode/bootstrap-datepicker/pull/369 но в продакшене его пока нет.
Пока вместе их лучше не использовать..
