### ISSUE TITLE
x-editable-yii 'select' Issue

### ISSUE THREAD

**Issue by kamran377** [vitalets/x-editable-yii#110]
Hi:
I;m using the x-editable extension to provide inline-edit support in cgridview. The text inline edits are working fine but when i try to use the editable for a column that is referenced from another table. I'm using following code

array (
                                    'name'=>'category_id', //
                                    'value'=>'$data->category->name',
                                    'filter'=>false,
                                    'class' => 'editable.EditableColumn',
                                    'editable' => array(
                                        'type' => 'select',
                                        'url' => 'updateName',
                                        'model'=>$model,
                                        'attribute'=>'category_id',
                                        'apply'=>true
                                    )
                        )

There are no errors on the console but the column does not converted to link (its not editable). I'm using Chrome and latest version of x-editable

![image](https://cloud.githubusercontent.com/assets/7840072/3219012/ff99d944-eff0-11e3-8420-7194f15a7ebb.png)

**Comment by kamran377** [comment]
here is my config file
'editable' => array(
            'class'     => 'editable.EditableConfig',
            'form'      => 'bootstrap',        //form style: 'bootstrap', 'jqueryui', 'plain' 
            'mode'      => 'inline',            //mode: 'popup' or 'inline'  
            'defaults'  => array(              //default settings for all editable elements
               'emptytext' => 'Click to edit'
            )
        ),

**Comment by Julian-B90** [comment]
have you add category_id to your rule in the model?
