### ISSUE TITLE
error:Alias "protected.components.widgets.tlbExcelView" is invalid. 

### ISSUE THREAD

**Issue by aahh01** [vitalets/x-editable-yii#113]
Followed the same procedure but getting an error.i downloaded tlbexcelview file and placed it in protected/components/widgets folder but getting the error.Not able to identify what is wrong.  Please help me as soon as possible....

**Comment by Julian-B90** [comment]
Hi aahh01,
This is the x-editable Plugin (http://x-editable.demopage.ru/) not the tlbExcelView.

**Comment by aahh01** [comment]
i am actually a newbie so not understanding how to resolve it.please can
you help me by telling whats the error and how can i get it solved..please
from past one week i am struggling..help this poor girl.

Actually i want to import my gridview data to excel from admin page without filter search option.By just providing an export button in admin page.

**Comment by Julian-B90** [comment]
watch here:
http://www.yiiframework.com/extension/tlbexcelview/ 
and 
https://github.com/tellibus/tlbExcelView

**Comment by aahh01** [comment]
Hi good morning,
                        I followed the same procedure but i got that error.

**Comment by aahh01** [comment]
Hi,
   Can  you tell me the other way of exporting the data to excel?

**Comment by aahh01** [comment]
Hi
   I used eexcelview and got the output,dont know why tlbexcelview didnt
work out.

Thank You,

**Comment by aahh01** [comment]
please can anyone tell how to add header,title to the excel sheet using
this eexcel.
