### ISSUE TITLE
Editable Field not appearing after new record, when grid is empty

### ISSUE THREAD

**Issue by alexiscps** [vitalets/x-editable-yii#117]
I have a grid (TbExtendedGridView or CGridView, tried with both). When the grid displays record already there, adding a new x-editable record function correctly. After insertion, and grid update, the record appears normally with "Empty Text" etc.

When the grid has no records on it, the exact same operation inserts a record, refreshes the grid, but only the id appears (not x-editable). Any other x-editable field appears empty and of course non-editable.

This appears only if the grid has no previous records. If there is one record ore more, everything works fine.

Any ideas?

**Comment by uldisn** [comment]
Before calling widget TbExtendedGridView  add record, if no records. Real example:
https://github.com/DBRisinajumi/trucks/blob/master/views/vtrcTruck/_view-relations_grids.php#L46

**Comment by alexiscps** [comment]
It could be a solution in another case. In my case, i need the grid to appear empty, and then add record into it. Isn't there a way to activate x-editable on a empty grid?

**Comment by ducnguyenhuy-agilityio** [comment]
@alexiscps: After new record, you can check if that's first record, then you reload page via javascript. That's solution that I'm using.

**Comment by Julian-B90** [comment]
@alexiscps i hope your problem was fixed.
I close this issue when you have any question please open a new issue
