### ISSUE TITLE
Cannot Manually Register Bootstrap, forced to use Bootstap Extension

### ISSUE THREAD

**Issue by surfer190** [vitalets/x-editable-yii#119]
<pre> public function registerAssets()
    {
        $am = Yii::app()->getAssetManager();
        $cs = Yii::app()->getClientScript();
        $form = yii::app()->editable->form;
        $mode = $this->mode ? $this->mode : yii::app()->editable->defaults['mode'];

        // bootstrap
        if($form === EditableConfig::FORM_BOOTSTRAP) {
            if (($bootstrap = yii::app()->getComponent('bootstrap'))) {
                $bootstrap->registerCoreCss();
                $bootstrap->registerCoreScripts();
            } else {
                throw new CException('You need to setup Yii-bootstrap extension first.');
            }
</pre>

You are force to register the bootstrap extension

**Comment by acorncom** [comment]
@surfer190 See Pull Request #115 that I opened (and that has been merged), should resolve your issue.

**Comment by surfer190** [comment]
Just for anyone who doesn't know it is in the `dev` branch.

`git checkout dev`

But this does not solve my problem.

I have registered bootstrap manually in layout as:

```
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/bootstrap.min.js'); ?> 
<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/css/bootstrap.min.css');?>
```

**Comment by surfer190** [comment]
So: `OR
include Bootstrap js and css manually:`

Does not apply anymore? 

found at: http://x-editable.demopage.ru/

**Comment by Julian-B90** [comment]
what is now your problem?

**Comment by surfer190** [comment]
The problem is that the yii bootstap extension is required however the documentation specifies that bootstrap css and js can be added manually.
