### ISSUE TITLE
Issue with Select2 in Chrome Browser

### ISSUE THREAD

**Issue by ckudikala-eprosoft** [vitalets/x-editable-yii#121]
The example did not work as expected even for "Bootstrap inline" or "Bootstrap popup".

The probelm is when user clicks on "ul.select2-choices" to display list of options,  its parent the div with class "popover" hides.

you can checkout the demo url:
http://x-editable.demopage.ru/index.php?r=site/widgets#select2
Chrome Version : Version 37.0.2062.120 m
Screen1
![screen1](https://cloud.githubusercontent.com/assets/781712/4392473/c0ffc56e-440e-11e4-9d70-58e4cddbf72c.png)

---

Screen2
![screen2](https://cloud.githubusercontent.com/assets/781712/4392474/c0ffca64-440e-11e4-876b-0cbd6785b8da.png)

**Comment by Julian-B90** [comment]
The new update from x-editable 1.4.6 to 1.5.1 fixes that issue
