### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by alexandernst** [vitalets/x-editable-yii#131]
I'm using x-editable 1.5.1 and this patch https://github.com/vitalets/x-editable/pull/724/files with Yii 1.1.16 and there are no visible problems. Can't assure there are no problems at all, but at least what I have tested so far is working right.

So... can we get a quick upgrade to 1.5.1 for Yii 1.1.16, please?

**Comment by Julian-B90** [comment]
Update the dev branch.
https://github.com/vitalets/x-editable-yii/commit/3df4f043263f076e609d1244afc5565ebdf45a93
