### ISSUE TITLE
data-pk in EditableColumn

### ISSUE THREAD

**Issue by tugas** [vitalets/x-editable-yii#17]
Does data-pk is read before is sent to server for the modification? In my case data-pk is a composed primary key and i have to allow the changes is certain values that are the primary key, the first request goes fine however the second one misses the pk it does not exist any more because it was changed.
on success  i wrote this

'success'=>"js:function(response, newValue){ $(this).attr('data-pk', response); }",

it changes the data-pk but it is not sent, only the page loaded value is.

Can you help with this?
--------------------------(UPDATE)
Ok i have been digging around and triggered a update of the grid solved my problem and solved also the update for the buttons key for deletion e update

**Comment by vitalets** [comment]
composite pk should work correct in 1.1.0
