### ISSUE TITLE
EditableColumn should be able to be used with CArrayDataProvider as well as CActiveDataProvider

### ISSUE THREAD

**Issue by ciarand** [vitalets/x-editable-yii#21]
Hi,

When attempting to use EditableColumn with CArrayDataProvider (say in the case of wanting to use a `HAS_MANY` relationship, eg `$meal->ingredients`), EditableColumn throws an exception because the grid is not an instanceOf CActiveDataProvider.

When commenting the CActiveDataProvider check out, the column works as expected with the CArrayDataProvider, so this seems to be an unnecessary restriction. I'll create a pull request that adds an allowance for CArrayDataProvider as well.

**Comment by vitalets** [comment]
hi, you are using array of model objects, right?
Otherwise I expect it to fail as CModel methods are used internally. 
But you are right,  we can currently check the model itself (not the provider of data)

**Comment by ciarand** [comment]
I'm not sure I understand.

When I'm creating the `CArrayDataProvider`, I'm doing so with something similar to the following code:

``` php
new CArrayDataProvider($meal->mealIngredients, array('keyField' => 'meal_ingredients_id'));
```

Since both `CArrayDataProvider` and `CActiveDataProvider` provide the same information to the extension (e.g. full access to `$data`, etc.), I believe they should both work. I haven't done a full set of tests, but the editable columns continue to work as expected on my system when using a `CArrayDataProvider`.

Let me know if I've misunderstood something. I'd love to get this working correctly in the main branch.

**Comment by vitalets** [comment]
you are correct.
The exception will come if someone will use simple php array here

``` php
new CArrayDataProvider(array(...), array('keyField' => 'meal_ingredients_id'));
```

I'll try to add workaround for both cases.
