### ISSUE TITLE
Using more then one input field?

### ISSUE THREAD

**Issue by izemize** [vitalets/x-editable-yii#27]
It possible?

http://vitalets.github.io/x-editable/demo.html (like address)

**Comment by vitalets** [comment]
generally yes. You should create js file with new input type and include it on page.
After then you can write:

```
 $this->widget('editable.EditableField', array(
'type' => 'mytype',
'model' => $user,
'attribute' => 'user_name',
'url' => $this->createUrl('site/updateUser'),
'placement' => 'right',
));
```

Note: this approach assumes update of single field in db from several inputs. 
If you want to update several fields in one request - it's not easy possible.
