### ISSUE TITLE
Use of X-Editable causes widescale CSS changes

### ISSUE THREAD

**Issue by ratfish32** [vitalets/x-editable-yii#28]
I've noticed that when I use X-Editable within a Yii View, the blueprint CSS gets changed and the view looks different then the rest of the views within the website.  If I remove the X-Editable widget use from the view, then it goes back to the standard look of the web app.  What am I missing?  Does use of X-Editable require that you adopt the bootstrap CSS theme for your site?

**Comment by vitalets** [comment]
hi, have you set `form` option via EditableConfig ?
http://x-editable.demopage.ru/index.php?r=site/components#EditableConfig
