### ISSUE TITLE
Different values for text and textarea

### ISSUE THREAD

**Issue by kirsty-forrester** [vitalets/x-editable-yii#3]
I'm using an EditableField textarea and am trying to have different values for the text and value variables so that I can show parsed HTML/bbcode/smileys but use the plain text versions for editing, example below:
![xeditable](https://f.cloud.github.com/assets/2790243/38505/32da9942-54f2-11e2-8709-aa4cd4ff746c.png)

I have added options for both text and value to my widget, but when I click the text is still used as the textarea value:

![xeditable2](https://f.cloud.github.com/assets/2790243/38512/7b391074-54f2-11e2-928c-0d44d00e5f27.png)

I think this is because the data-value attribute doesn't get added to the HTML options array. The `$this->htmlOptions['data-value'] = $this->value; // line 362`
line is inside of this if statement:
`if ($this->_prepareToAutotext) { // line 340`

Your comment on line 339 says, "if preparing to autotext we need to define value directly in data-value," but to me it seems like data-value is also needed if you want to have different values for the text and textarea. Is that right or am I missing something?

If it's right, I think line 362 needs be moved outside of that if statement.
If it's not right, please explain how to have different values for text/value. Should I just add the data attribute manually using htmlOptions?

This is my first ever GitHub issue. I hope I did it right! Thanks.

**Comment by vitalets** [comment]
hi, 

you should use `display` callback. 
Please have a look on this: http://jsfiddle.net/xBB5x/223/

ps: you have a very good start :) good luck!

**Comment by kirsty-forrester** [comment]
Hi, thank you for letting me know about display. I must have missed that!

If anyone else reads this and is trying to do the same thing, here is the option I added to my xeditable config:

``` php
'display' => 'js: function(value) {
     var original = $(this);
     $.ajax({
         url: "'.Yii::app()->createUrl('comment/getParsedContent', array('id' => $data->id)).'",
         success: function(data) {
             original.html(data);
     }    
 });
}',
```

The getParsedContent is my method that echoes out the parsed HTML. It's an extra ajax call but it seemed like the easiest way to do it (maybe even the only way?)
