### ISSUE TITLE
TbEditableColumn validate

### ISSUE THREAD

**Issue by githubjeka** [vitalets/x-editable-yii#30]
How to change scenario for $data? By default It is 'update'. My scenario for attribute1 and for oneUser is set 'MySuperScenario1' , for  attribute2  and for OtherUser is set 'MySuperScenario2'.
The attributes not safe, because I can not change them. :/

**Comment by vitalets** [comment]
hi, scenario should be `editable` if you are using `EditableSaver` class.. And you can change it depending on attribute or user id. 

``` php
$es = new EditableSaver('User'); 
$es->scenario = $_POST['name'] == 'attribute1' ? 'MySuperScenario1' : 'MySuperScenario2';
$es->update();
```

**Comment by githubjeka** [comment]
I have a problem with display of this column, not saving.
Суть по русски - http://www.yiiframework.ru/forum/viewtopic.php?f=3&t=11989

This problem is unlikely to directly involve your permission. Thanks.
