### ISSUE TITLE
the x-editable js  not support bootstrap icons 

### ISSUE THREAD

**Issue by hfvoip** [vitalets/x-editable-yii#31]
hi, the x-editable js  not support bootstrap icons 
I want status display an pause button ,   < i class="icon-pause" ></ i >, but it is not working 

```
array(
        'class' => 'editable.EditableColumn',
        'name' => 'status',
        'value'=>'$data->display_status()',
        'type'=>'raw',

        'headerHtmlOptions' => array('style' => 'width: 110px'),
        'editable' => array(
        'type' => 'select',
        'url' => $this->createUrl('offerv2/updateinline'),
        'source' => $this->createUrl('offerv2/listofferstatus'), 
        'placement' => 'right',
        )

    ) ,
```

**Comment by vitalets** [comment]
hi, so your `$data->display_status()` method returns `< i class="icon-pause" ></ i >`, right?
it seems to be related with 'empty detection' of x-editable that now uses jquery `.text()` method, not `.html()`.
I plan to add option for that in nexr release of x-editable.
thx!

**Comment by vitalets** [comment]
since 1.3 (just released) it should work.
if not, please reopen this issue.
