### ISSUE TITLE
Bug with JSON Source with Zero-Indexed Return array via ajax request

### ISSUE THREAD

**Issue by Bhoft** [vitalets/x-editable-yii#37]
There seams to be some "bug" when the source ajax request is returning a zero-indexed array.
e.g. 

```
    echo CJSON::encode(array(0=>'text for value 0', 1=>'text for value 1')); 
```

returns 

```
    ["text for value 0", "text for value 1"]
```

to the js extension.
this is a "normal" issue for yii see https://github.com/yiisoft/yii/issues/2094

If i return following in my ajax source function x-editable works normally.

```
echo '{"0":"text for value 0","1":"text for value 1"}';
```

Sadly Yii won't fix this CJSON issue because they saying its still the correct js object.

The problem is that the json string ["text for value 0", "text for value 1"] is both a object but also is an array for this call 

```
 makeArray: function(data) {
...
 if($.isArray(data)) { //array
...
```

if this line would been changed to following the issue that the wrong if clause code will be processed would be fixed.

```
..
if($.isArray(data) && typeof data != 'object') { //array
..
```

**Comment by Bhoft** [comment]
i have just updated to the latest svn version had the 1.0.0 before so this seems be fixed in the meantime.

**Comment by Bhoft** [comment]
Sry i have to reopen,,.. when i am testing the svn version i had some other yii code as a workarround for the zero indexed array where a array is created with value and text parameters.

```
  public function actionGetStatusList()
    {   
        $options=array(0=>'text for value 0', 1=>'text for value 1');
        $this->layout=false;
        header('Content-type: application/json');
        $return_array=array();
        foreach($options as $k => $v)
            $return_array[]=array('value'=>$k,'text'=>$v);

        //echo CJavaScript::jsonEncode($options);
        echo CJavaScript::jsonEncode($return_array);
        Yii::app()->end(); 
    }
```

**Comment by vitalets** [comment]
so the question is how do we want to treat source like `['text1', 'text2', 'text3']`
There are two cases:
1. value = text
2. value = index

Both are possible in different situations, and i think it's better to keep current behavior (use value = text).
But for easy dealing with arrays I can add one static method, `Editable::source()` that will always return source in text/value json format. This format is the best because guarantees order of items in list.

**Comment by kvpt** [comment]
I dont know if I should create a new issue, but the select2 plugin need a different format : {id: '', text: ''} and the method dont handle this case.
