### ISSUE TITLE
php version < 5.3 with Lambda functions problem

### ISSUE THREAD

**Issue by Bhoft** [vitalets/x-editable-yii#39]
In the Editable.php there is a usage of a lambda function (inline function) on the array map call:

```
$pk = join('_', array_map(function($k, $v) { return $k.'-'.$v; }, array_keys($pk), $pk));
```

this code would produce an error on php versions < 5.3.0  afaik.
Maybe it would be better to either has a version check or use create a class function.
Somthing like this:

```
 change the code to:
 $pk = join('_', array_map(array($this,'map_function'), array_keys($pk), $pk));

and add this function
 public function map_function($k, $v)
 {
        return $k.'-'.$v;
 }

```

So the extension also works in earlier php versions or add some php version requirements if the code won't been changed.

not really an issue but i thought this is the best place to mention it.
regards Horizons

**Comment by thyseus** [comment]
I also encountered this problem on an ancient php <5.3 setup,so i also vote for applying this patch. 
Unfortunately there are still a LOT of old php versions around :-(
