### ISSUE TITLE
htmlarea

### ISSUE THREAD

**Issue by chameleon82** [vitalets/x-editable-yii#4]
Hello! Great extension. I think, it must be reached with html-editor. For example:

 $this->widget('editable.EditableField', array(
   'type' => 'htmlarea',

I think, the best way for it is integrate Imperavi Redactor widget with x-editable (https://github.com/yiiext/imperavi-redactor-widget)

Thanks

**Comment by vitalets** [comment]
hi, in the latest x-editable itself I've done https://github.com/jhollingworth/bootstrap-wysihtml5 (it's not in yii extension yet but will be added)
Redactor is also looks very pretty but really not sure is it make sence to have both..

**Comment by jacmoe** [comment]
I tried to implement this, but no luck.

Any chance that you might implement this soon? :)

**Comment by hellvesper** [comment]
Здравствуйте. 
Есть ли какой-нибудь способ пока вручную связать x-editable и imperavi redactor для Yii? Хотя бы в двух словах =)

**Comment by vitalets** [comment]
Привет! Я думаю, тут лучше без x-editable, у них же есть встроенная edit-in-place
http://imperavi.com/redactor/examples/click-to-edit/
