### ISSUE TITLE
Editables quit working in TbListView after the page navigation is clicked

### ISSUE THREAD

**Issue by ratfish32** [vitalets/x-editable-yii#46]
I'm trying to use a editable.EditableField with a bootstrap.widgets.TbListView that has paging Turned on.  All the Editable fields work great until you use the page navigation of the ListView.  Once you page two page 2, the editables quit working.  If you click the links, nothing happens.  No editable window pops up.  Even if you page back to page 1, then still do not work.  Any idea what might be wrong with my implementation?

Here is an example of one of the Editables:

<?php
                  $this->widget('editable.EditableField', array(
                  'type' => 'text',
                  'model' => $data,
                  'attribute' => 'Quantity',
                  'url' => $this->createUrl('list/updateShoppingListItem'),
                  'placement' => 'right',
                  ));
               ?>

Here is the implementation of the TbListView:

<?php $this->widget('bootstrap.widgets.TbListView',array(
   'id'=>'lvwShoppingList',
    'dataProvider'=>$dataProvider,
    'itemView'=>'_view',
)); ?>

**Comment by pavshuk** [comment]
It is because js inserted in page after table, and Ajax don't raffle it for
update table without that js.  You Can turn off Ajax tabulation.

It's not clever, but work.  In my project it need to be repeared.
06.06.2013 10:19 ÐÏÌØÚÏ×ÁÔÅÌØ "ratfish32" notifications@github.com
ÎÁÐÉÓÁÌ:

**Comment by pavshuk** [comment]
I read CClientScript. It can add script in :
     \* <li>CClientScript::POS_HEAD : the script is inserted in the head section right before the title element.</li>
     \* <li>CClientScript::POS_BEGIN : the script is inserted at the beginning of the body section.</li>
     \* <li>CClientScript::POS_END : the script is inserted at the end of the body section.</li>
     \* <li>CClientScript::POS_LOAD : the script is inserted in the window.onload() function.</li>
     \* <li>CClientScript::POS_READY : the script is inserted in the jQuery's ready function.</li>

No one variant don`t valid for us. It`s ideal for us if we add script right after editable widget.

May be add option to widget like a  'scriptAddPosition' with values [default, afterWidget]?

**Comment by vitalets** [comment]
made it working. It will be released in 1.3 soon, but you can checkout `dev` branch to try it.
New docs will be published after release.

``` php
//listview
    $widget = $this->widget('bootstrap.widgets.TbListView', array(
    'id' => 'listview',
    'dataProvider' => $dataProvider,
    'itemView' => 'application.views.common.listviewitem',
    ));
    //for update editables after ajax sort and pagination
    Editable::attachAjaxUpdateEvent($widget);


//listviewitem
Username:

$this->widget('editable.EditableField', array(
'type' => 'text',
'model' => $data,
'attribute' => 'user_name',
'url' => $this->createUrl('site/updateUser'),
'placement' => 'right',
'liveTarget' => $widget->id, //for live update
));
```

**Comment by pavshuk** [comment]
it`s works. Thanks.

**Comment by sashaguru** [comment]
Memory leak problem:
Editable.php
Line 523: $script .= "\n $('body').on('ajaxUpdate.editable', function(e){ if(e.target.id == '".$this->liveTarget."') yiiEditable(); });";
Replace with: $script .= "\n $('body').off('ajaxUpdate.editable.".$this->liveTarget."_".$this->htmlOptions['rel']."').on('ajaxUpdate.editable.".$this->liveTarget."_".$this->htmlOptions['rel']."', function(e){ if(e.target.id == '".$this->liveTarget."') yiiEditable(); });";

**Comment by ratfish32** [comment]
The new LiveTarget property fixed my issue with the EditableFields not working after clicking the page navigation was clicked.  It introduced a new problem with my ajaxLinks, though, in that they quit working at all.  If I comment out this line, then they start working again:

Editable::attachAjaxUpdateEvent($widget);

Here is an example ajaxLink code snipped that no longer works with the LiveTarget change:

<?php echo CHtml::ajaxLink("Mark Complete",
                                       array("list/complete", "id" => $data->ShoppingListItemId,"ajax"=>1),
                                       array("success"=>'js:function(data){$.fn.yiiListView.update("lvwShoppingList",{});}', "type"=>"get",),
                                       array('confirm'=>'Are you sure you want to mark this item complete?')); ?>

Anyone have any idea what is wrong?

Aaron
