### ISSUE TITLE
server-side validation with scenario.

### ISSUE THREAD

**Issue by pavshuk** [vitalets/x-editable-yii#48]
Now validation work with 'editable' scenario. 
When we create widget('editableField') we can get scenario by calling getScenario and save it in js or html.
And then got it in EditableSaver.

As for me it`s more interesting decision. In that case work with editable and ordinary form would be the same.

**Comment by vitalets** [comment]
wonderfull idea, thanks!

**Comment by pavshuk** [comment]
I comment line of code in commit

**Comment by me23** [comment]
Don't you think it is an security issue to depend on scenario send by post request?

I would prefer to have a precedence if i set the scenario on the server..
For example something like this in EditableSaver:

public function update(){
...
if(!$this->scenario){
    $this->scenario = yii::app()->request->getParam('scenario');
}

So in controller if i set an scenario the post scenario will be ignored...
