### ISSUE TITLE
Problem with "source with count = 1 is Yii route"

### ISSUE THREAD

**Issue by schmunk42** [vitalets/x-editable-yii#5]
I had some headaches, finding out, that an array with only one entry is treated as a Yii route. ('type'=>'select')

Could you either add another option like `sourceRoute` or tell me a workaround, if my select field only has one entry or what if my route needs additional params?

**Comment by vitalets** [comment]
yes, it's a bit confusing..
If route needs additional params the most elegant workaround is 

```
'source' => CHtml::normalizeUrl(array('site/list', $params))
```

but when source has 1 element - as I checked in code - not possible currently.
It should be definetly fixed: just check if the first element has format `array('value' => ..., 'text' => ...)` then not treat it as route.
You solution with `sourceRoute` also may be possible to exclude confusing at all, I will review the code. Just trying to keep less number of options.

**Comment by schmunk42** [comment]
Wouldn't it be an option to hand over the URL always as a string?
