### ISSUE TITLE
EditableDetailView should be more like CDetailView

### ISSUE THREAD

**Issue by mdeweerd** [vitalets/x-editable-yii#50]
The EditableDetailView should be more like http://www.yiiframework.com/doc/api/1.1/CDetailView .

For instance, I can use the 'type' parameter for a field in CDetailView to format the field according to a method in Yii::app()->format, but is not available in EditableDetailView.

For instance, I have a 'formatLocalDatetimeSeconds' in the formatter and while the following works with the CDetailView, the 'type' is ignored in the editable version.

``` php
        array(
                'name'=>'time',
                'type'=>'localDatetimeSeconds',
        ),
```

**Comment by vitalets** [comment]
hi, it looks good. 
The problem is that format specification in Yii may be different from format specification of js plugins used in editable. For example datetime format: `Y/m/d` in php against `yyyy/mm/dd` in datepicker.

**Comment by mdeweerd** [comment]
As far as I remember, the datepicker format supports internationalisation - at least I have a date field in my project displayed in local time with a date picker.

In this particular case, I (can) live without the datepicker (a datetime picker would be more appropriate), but editable displays an empty field instead (when I just have 'name'=>'time) (which is either a bug or improper use of my part).

Anyway, the suggestion is to make it look more like CDetailView.  The exemple is for a date, but also applies to other types.  Basically if I change CDetailView in EditableDetailView, the functionnality should remain the same except that fields become editable.

Therefore, in this case, if the specified 'type' can not be interpreted by 'editable', then 'editable' should simply consider the field as 'text'.  If the developer wants an editable field, he then has too change the 'type' as specified originally or use further editable options to adjust the configuration.

**Comment by vitalets** [comment]
Reviewed this issue. Currently we have `apply` parameter to turn on/off editable functionality for particular attribute or whole EditableDetailView. E.g.:

``` php
$this->widget('editable.EditableDetailView', array(
    'data'         => $user,
    'apply'       => false,  //attributes not editable by default
    'attributes' => array(
       'user_name', //will not be editable
       'user_comment', //will not be editable
        array( 
            'name' => 'user_status', //will be editable 
            'editable' => array(
                'type'   => 'select',
                'source' => $this->createUrl('site/getStatuses'),
                'apply' => true, //we must set apply to overwrite defaults
            )
        ),

...
));
```

It is usefull if you need to have only one/two editable attributes in big CDetailView.
Seems to solve the issue.
