### ISSUE TITLE
Single checkbox

### ISSUE THREAD

**Issue by pavshuk** [vitalets/x-editable-yii#51]
I found formula for create single checked editable widget by Yii:

```
array( 
    'type' => 'checklist',
    'model' => $this,
    'attribute' => $name,
    'url' => Yii::app()->createUrl('/'.$this->getClassId().'/updateEditable'),
    'source' => array(1=>'Checked'),
            'emptytext' => 'Not checked',
        )
```

In DB I have row (`INT NULLABLE`).

In model I add:

```
function rules(){
    return array(array('exclusive', 'filterArrayToVal', 'on' => 'insert, view'))
}

public function filterArrayToVal($attribute){
    if(is_array($this->$attribute) && count($this->$attribute)==1) {
        $val =$this->$attribute;
        $this->$attribute = $val[0]; 
    }else{
        $this->$attribute = 0;
            }
}
```

As result I have values 1 and 0.

**Comment by vitalets** [comment]
good usecase, thx!
have you also tried `BooleanValidator` ? maybe it will do job instead of custom function..

**Comment by pavshuk** [comment]
no, `booleanValidator` not work. There are we have array() and array(1) values.

**Comment by vitalets** [comment]
I looked more deep in this issue: it's more about how you store boolean values in db: 
e.g int (1 / 0), or boolean (true / false)...
For your case when storing 1 for `true` and 0 for `false` you can use `filter` validator to adjust values:

``` php
array('checked', 'filter', 'filter' => 'count'),
```

but if you want to store 1 for `true` and `NULL` for `false`, you should change it to:

``` php
array('checked', 'default', 'value' => null),
```
