### ISSUE TITLE
error : Your request is invalid. What url to put ?

### ISSUE THREAD

**Issue by jtaylor007** [vitalets/x-editable-yii#52]
I'm a newbie in php and Yii and fine this extension is excellent. I have an error when i want to update a column in a gridview. Maybe it's not an issue

error : Your request is invalid.

Maybe it's the url. Please help me.

in my view page  
   <?php $this->widget('bootstrap.widgets.TbExtendedGridView',array(
    'id' => 'devoirs-grid',
    'type' => 'striped bordered',
    'fixedHeader' => true,
    'headerOffset' => 40, // 40px is the height of the main navigation at bootstrap
    'dataProvider' => $model->search(),
    'filter' => $model,
    'columns' => array(
        'name',
       // 'sujet',
        'date_donnee',
        'date_due',
        'points_total',
         array(
           'class' => 'editable.EditableColumn',
           'name' => 'points_total',
           'headerHtmlOptions' => array('style' => 'width: 110px'),
           'editable' => array(    //editable section
                //  'apply'      => '$data->user_status != 4', //can't edit deleted users
                  'url'        => $this->createUrl('devoirs/update'),
                  'placement'  => 'right',
              )  
        ),

What url to put in 'url' options.

Where to write update code ?

Thanks

**Comment by vitalets** [comment]
hi, have you wrote `actionUpdate` in `devoirs` controller ?
e.g. 

``` php
class DevoirsController extends Controller
{
 ...
    public function actionUpdate()
    {
    $es = new EditableSaver('Devoir');
    $es->update();
    }
```

**Comment by jtaylor007** [comment]
Thanks a lot ! It's working now. I've wrote update() in place of actionUpdate() 

:+1:

**Comment by vitalets** [comment]
you're welcome! :)
