### ISSUE TITLE
Installed Editable, field changes but in DB the is no changes

### ISSUE THREAD

**Issue by elasti-co** [vitalets/x-editable-yii#53]

**Comment by pavshuk** [comment]
show widget and saver code
25.06.2013 6:02 ÐÏÌØÚÏ×ÁÔÅÌØ "Artem Willmann" notifications@github.com
ÎÁÐÉÓÁÌ:

**Comment by elasti-co** [comment]
Sorry, I found my mistake. In Controller I did not change Model name.
By the way why is it necessary to indicate Model name if I already transfer Model in "data"? Isn't it clear that I would like to save to the same Model? )

**Comment by pavshuk** [comment]
I think you still made mistake. Show me widget code.
25.06.2013 15:19 ÐÏÌØÚÏ×ÁÔÅÌØ "Artem Willmann" notifications@github.com
ÎÁÐÉÓÁÌ:

**Comment by elasti-co** [comment]
$this->widget('bootstrap.widgets.TbEditableDetailView', array(
    'id' => 'region-details',
    'data' => GeoCountry::model()->findByPk(2),
    'url' => $this->createUrl('page/editable'),  //common submit url for all editables
    'attributes'=>array(
        'id',
        'lang_ru',
    )
));

**Comment by pavshuk** [comment]
You are right. no error.

ó Õ×ÁÖÅÎÉÅÍ, ëÏÌÏÓÏ× ðÁ×ÅÌ ðÁ×ÌÏ×ÉÞ.

2013/6/25 Artem Willmann notifications@github.com

**Comment by elasti-co** [comment]
Thank you, now it works. But I just wanted to notice that it's not necessary to indicate Model name in Controller.

**Comment by vitalets** [comment]
hi, @willmann 
if your question is why we pass model name into EditableSaver - it's mainly for security reason. otherwise there maybe a method that can change any model in app that basically is not needed for normal work.
