### ISSUE TITLE
Yii + Edit COOKIE record

### ISSUE THREAD

**Issue by elasti-co** [vitalets/x-editable-yii#54]
Is it possible to edit COOKIE record using X-Editable? I need it to Select city if it's not detected automatically.

**Comment by vitalets** [comment]
yes, you should use basic `Editable` widget that is not related to ActiveRecord.

**Comment by elasti-co** [comment]
Thanks a lot for support and for such a beautiful extension.

**Comment by vitalets** [comment]
you are welcome :)
