### ISSUE TITLE
EditableField Select with CFormModel

### ISSUE THREAD

**Issue by germanliu** [vitalets/x-editable-yii#57]
Hi, is it possible to configure an EditableField of type Select from a CFormModel instead of an CActiveRecord? When I input the 'source', I want it to be a simple php array... something similar to: //'source'    => Editable::source(array(1 => 'Status1', 2 => 'Status2')).... when I try this it says that my model doesn't have a IsNewRecord method, which makes sense since its a CFormModel and not an CActiveRecord.

Thanks!

**Comment by vitalets** [comment]
hi, it's good feature! i've added support of CFormModel in `dev` branch.
could you re-check on your side?
thx!

**Comment by vitalets** [comment]
On server side you can do whatever with attribute in `onAfterUpdate` event

``` php
    public function actionUpdateContactForm()
    {
        $es = new EditableSaver('ContactForm'); 
        $es->onAfterUpdate = function($event) {
            echo 'updated: '.$event->sender->attribute . ' to '. $event->sender->value;
        };
        $es->update();
    } 
```
