### ISSUE TITLE
How to disable an attribute that is safe

### ISSUE THREAD

**Issue by gunnit** [vitalets/x-editable-yii#58]
Iam having the issue of not being able to make a safe attribute not editable , is there a fix for this ?

**Comment by nkostadinov** [comment]
how about you create a scenario where this attr is not safe ?

**Comment by pavshuk** [comment]
show php code of editable element.

**Comment by nkostadinov** [comment]
i saw you posted in the forum and there was very nice explanation there. Just add 'apply'=>false to the params of the editable.

**Comment by pavshuk** [comment]
apply work not for all types.
use  'options' => array('disable' = true);

2013/7/23 phreakbg notifications@github.com

**Comment by gunnit** [comment]
@pavshuk  still not working code below 

<?php $this->widget('editable.EditableDetailView', array(
      'data' => $model,
    //you can define any default params for child EditableFields 
    'url' => $this->createUrl('configMensile/updateConfigMensile'), //common submit url for all fields
    'params' => array('YII_CSRF_TOKEN' => Yii::app()->request->csrfToken), //params for all fields
    'emptytext' => __('nessun valore'),
    'attributes'=>array(
            array(
                'name'=>'idCompany.denominazione',
                'apply'=>false,
                'options' => array('disable' => true)
                ),
               array(
                    'name' => 'config_description',
                    'editable' => array(
                        'type'       => 'text',
                    )
                ),
                array( //select loaded from database
                'name' => 'data_sheet',
                'editable' => array(
                    'type'   => 'select',
                    'source' => Editable::source(array('1' => '1', '2' => '2', '3' => '3', '4' => '4', '5' => '5', '6' => '6'))
                 )
                ),
                array( //select loaded from database
                'name' => 'line_start',
                'editable' => array(
                    'type'   => 'select',
                    'source' => Editable::source($model->lineStartValues)
                 )
                ),

**Comment by vitalets** [comment]
hi @gunnit 
`'apply'=>false,` should do the job. 
Please put it into `editable` section:

``` php
 array(
'name'=>'idCompany.denominazione',
'editable' => array(
  'apply'=>false,
),
...
```
