### ISSUE TITLE
Composite primary key

### ISSUE THREAD

**Issue by olemara** [vitalets/x-editable-yii#6]
Your component looks very useful.

I ran across the problem of having a composite primary key:

 public function getSelector()
{
   return get_class($this->model) . '_' . $this->attribute . ($this->model->primaryKey ? '_' .    $this->model->primaryKey : '_new');
}

Any smooth workaround for this?

**Comment by vitalets** [comment]
hi, it's definitely a bug, 
Composite key should be converted to string here. something like:

```
if(is_array($this->model->primaryKey)) {
  foreach($this->model->primaryKey as $k => $v) {
     $selector .= $k.'_'.$v;
  }
}
```

If you test that it works correct I will appreciate pr.
Thanks!

**Comment by olemara** [comment]
Thanks for the reply,

Yeah somthing like that. My temporary solution was to have a helper function:

<pre>
    private function getPrimaryKeyAsString() {
        $pkString = NULL;
        if (is_array($this->model->primaryKey)) {
            $isFirst = TRUE;
            foreach ($this->model->primaryKey as $k => $v) {
                if ($isFirst) {
                    $pkString .= $k.'_'.$v;
                    $isFirst = FALSE;
                }
                else {
                    $pkString .= '-'.$k.'_'.$v;
                }
            }
        }
        else {
            $pkString .= $this->attribute . ($this->model->primaryKey ? '_' . $this->model->primaryKey : '_new');
        }
        
        return $pkString;
    }
</pre>

This is because it needs to be used in buildHtmlOptions() when setting $htmlOptions['data-pk'] if composite.

<pre>
        $htmlOptions = array(
            'href'      => '#',
            'rel'       => $this->getSelector(),
//            'data-pk'   => $this->model->primaryKey,
        );
        
        if (is_array($this->model->primaryKey)) {
            $htmlOptions['data-pk'] = $this->getPrimaryKeyAsString();
        }
        else {
            $htmlOptions['data-pk'] = $this->model->primaryKey;
        }
</pre>

htmlspecialchars does not like arrays.

Cheers!

**Comment by tugas** [comment]
I have commend across this problem what i did was the following

In the file EditableField.php

public function getSelector()
    {
        if (is_array($this->model->primaryKey)){
            return get_class($this->model) . '_' . $this->attribute . ($this->model->primaryKey ? '_' . CJSON::encode($this->model->primaryKey) : '_new');
        }else{
            return get_class($this->model) . '_' . $this->attribute . ($this->model->primaryKey ? '_' . $this->model->primaryKey : '_new');
        }

}

Line 330
      public function buildHtmlOptions()
    {
        //html options
        $htmlOptions = array(
            'href'      => '#',
            'rel'       => $this->getSelector(),
            'data-pk'   => is_array($this->model->primaryKey) ? CJSON::encode($this->model->primaryKey) :$this->model->primaryKey ,
        );
.....

The request will be sent to the server like an array pk={id1:value,id2:value }
Sorry for my bad writing skills in github comments
I hope this helps 
Regards
