### ISSUE TITLE
Browser freezes when we do a lot of pagginations

### ISSUE THREAD

**Issue by denisrudov** [vitalets/x-editable-yii#60]
Each click on next page make bigger delay between ajax start and ajax.success.
After about 10 - 15 clicks on next page invokes browser freezes.
the problem is in /editable/Editable.php 
#702 line.

maybe problem is in amount of the rows in my table. Yes. our table is very big. about 200 rows and 20 - 30 pages. 
so I think it happens each time when triggers ajaxUpdate.editable many times.

**Comment by vitalets** [comment]
hmm.. @Denisrudov could you make an experiment - click only between first and second pages many times. 
Does the freeze also appear?

**Comment by denisrudov** [comment]
I've fixed it for me in the next way: 
I got all generated codes for each editable element and put it in external JS file. I know that it's not a solution but it works for me.I mean that I got (editable(){<this_code_for_first_element> except if()... }),(editable(){<this_code_for_the_next_element>}) and so on. 
if I do this - all works fine. My browser is Chrome 28.0.1500.95 but also my client found the same issue in IE9, and Firefox(don't know version). 

yeap. I just tried - the same issue. I think editable() should be run only once.not for each element. because every widget includes this (editable(){...})();

**Comment by vitalets** [comment]
it seems some cumulative issue, but I can not detect it exatctly.
Could you show you code (if possible) ?
Are you using EditableColumn or ListView with EditableFields inside?

**Comment by bridennis** [comment]
Hi there,
I had the same problem and I dug up the solution.

What problem?
The script Editable.php has cyclic event handler:

(function yiiEditable() {
...
$('body').on('ajaxUpdate.editable', function(e){ if(e.target.id == '".$this->liveTarget."') yiiEditable(); });
...
}());

(see section after: //wrap in anonymous function for live update)

What the problem solution?
Just change
... $('body').on(' ..
on
... $('body').one(' ...

Have a nice day guys!
