### ISSUE TITLE
caching problem of source options

### ISSUE THREAD

**Issue by Bhoft** [vitalets/x-editable-yii#62]
Hi i have tried something because i didn't wanted any caching of the source options.

i tried to set 'sourceCache'=>false, which isn't possible atm (but it would be nice to have this).

Netherless as you know i use the editable columns in a gridview. And with my patch I have additional parameters which i can attach to the source url.

```
'source'    => 'js: function() {
                     var projectdetails_id=$(this).data().projectdetails_id;
                     return "?r=projectdetails/getProjectStatusList&projectdetails_id="+projectdetails_id+"&nocache=" + new Date().getTime();
                 }',
```

I just added a no cache timestamp so each request will be unique the additional parameters aren'´t an issue.

After clicking the editable link column the select options aren't rendered at all.
if i make add an alert after the ajax request for the source i see that the options are renderd, and the cache is filled. 

But the popup is closed somehow afterwards. So the editable in the column with a url as the source only works if cached. Then you have to click a second time so the data is fetched from the cache created before.

So there is some minor problem in the js code which i can't find :( but i guess for you this is an easy fix.

**Comment by vitalets** [comment]
@horizons2 could you make a jsFiddle demonstrating the issue with pur x-editable.
use this as starter template http://jsfiddle.net/xBB5x/195

**Comment by Bhoft** [comment]
Sry, 
i have created a fiddle  http://jsfiddle.net/xBB5x/1802/ and realized that it was correclty working there.
Therefore it has to be a js code i have in my application which i already found.

i have a global ajaxsetup in my app.

```
$.ajaxSetup({
    global: true,
    complete:function(xhr,status){
       ....
       //$('div.popover').remove();
       $('body').scrollspy('refresh');
    },
    error:function(jqXHR, textStatus, errorThrown){
        alert(errorThrown+' '+ jqXHR.status+': '+jqXHR.responseText);
        $("button").button("reset");
    }
    });
```

the problem was the $(div.popover).remove(); which i now removed and it works as expected.
sry about that :+1:
