### ISSUE TITLE
editing related fields

### ISSUE THREAD

**Issue by FrostBy** [vitalets/x-editable-yii#70]
Hi!
How can I edit a related field in this example
I have 3 tables: Countries, Requests and RequestsCountries
in Requests model:
'requestCountries' => array(self::HAS_MANY, 'RequestCountries', 'request_id'),
in Countries model:
'requestCountries' => array(self::HAS_MANY, 'RequestCountries', 'country_id'),
in RequestCountries:
'country' => array(self::BELONGS_TO, 'Countries', 'country_id'),
'request' => array(self::BELONGS_TO, 'Requests', 'request_id'),

Request may have multiple countries

Editable detailView is in Requests view file.
....
                array(
                    'name' => "????",
                    'editable' => array(
                        'type' => 'select2',
                        'source' =>Editable::source(Countries::model()->findAll(), 'id', 'title'),
                           'select2'=>array(
                               'multiple'=>true
                            )
                     )
                ),
....

**Comment by nima1981** [comment]
I am also interested in seeing a working example on how to implement this ...
