### ISSUE TITLE
Question: Number, formatted when showed but unformatted when being editted

### ISSUE THREAD

**Issue by dadinugroho** [vitalets/x-editable-yii#74]
I have problem with numbers. I put editable column on my gridview. before adding editable, I show the 'value' => 'number_format($data->price, 0, ".", ",")', 

Since, I added editable, the problem is aroused, User need to delete the thousand separator otherwise the value will be cut on the thousand separator. Second problem, after updating (user put number without thousand separator) the displayed value looks ugly (unformatted). 

Any help on this? Thank you in advance.

**Comment by dadinugroho** [comment]
I manage to remove the "," during edit by using below 

array(
            'class' => 'editable.EditableColumn',
            'name' => 'unitPrice',
            'header' => 'Harga',
            'type' => 'raw',
            'value' => 'CHtml::encode(number_format($data->unitPrice,0,".",","))',
            'htmlOptions' => array('style' => 'text-align: right;'),
            'editable' => array(
                'url' => $this->createUrl('/product/updateProdPrice'),
                'onShown' => 'js: function(e, editable) {
                                 editable.input.$input.val(editable.input.$input.val().split(",").join(""));
                             }',
                'options' => array(
                    'success' => 'js: function(response, newValue) {
                                     if(response.success) {
                                         return {newValue: response.newPrice};
                                     }
                                 }',
                ),
            ),
        ),

but not able to show the formatted value after edit finished. Although, I used success options. Any help on this?

**Comment by Bhoft** [comment]
You can also do this.
just set the data-value in the htmlOptions in the editable array part
'htmlOptions'=>array('data-value'=>'$data->unitPrice'),

Then the "unformated" value is used for editiing. The only "Problem" you have now is that you have to format the "newValue" output in JS. For me i always to a grid refresh after i change a value and get the formated text back. Where $grid_id is filled with the id of the grid.

I guess there is no other possibility so either format your output in js or do an grid refresh.

like this 
array(
'class' => 'editable.EditableColumn',
'name' => 'unitPrice',
'header' => 'Harga',
'type' => 'raw',
'value' => 'CHtml::encode(number_format($data->unitPrice,0,".",","))',
'htmlOptions' => array('style' => 'text-align: right;'),
'editable' => array(
'url' => $this->createUrl('/product/updateProdPrice'),
'htmlOptions'=>array('data-value'=>'$data->unitPrice'),
'options' => array(
'success' => 'js: function(data) {
      $.fn.yiiGridView.update("'.$grid_id.'");
}',
),
),
),

**Comment by Julian-B90** [comment]
Is is fixed with this issue https://github.com/vitalets/x-editable-yii/issues/71
