### ISSUE TITLE
namespace issues

### ISSUE THREAD

**Issue by graymouser** [vitalets/x-editable-yii#9]
Using namespaces breaks extension

e.g. instead of User model the model is application\models\User

fix is, everywhere get_class is used in extension, instead use my_get_class

function my_get_class($object)
{
    return str_replace('\','_',get_class($object));
}

also, in line 78 of EditableSaver, do not use ucfirst
i.e.  
$this->modelClass = ucfirst($modelClass);
becomes
$this->modelClass = $modelClass;

hope this helps someone

**Comment by vitalets** [comment]
thank you! It seems to be common problem, as I see similar `get_class` usage in bootstrap extension.
I will fix in nearest release.
