### ISSUE TITLE
MAINTAINER NEEDED!

### ISSUE THREAD

**Issue by vitalets** [vitalets/x-editable-yii#90]
hi everyone, 

my heart is bleeding when I see several-month-aged issues here, but currently I really can't find time to support x-editable-yii. Also my work is not related with yii already for a long time and it's became difficult for me to find and understand problems.
To not let this project get frozen I would be very gracefull if someone will be ready to maintain and support it. Mainly the work is porting features from root [x-editable](https://github.com/vitalets/x-editable) to this extension.
I'm continuing to maintain root x-editable and will provide any personal help needed for x-editable-yii.
Thanks a lot!

**Comment by DrMabuse23** [comment]
well have not time too but maybe its better place this in Yii Forum

**Comment by vitalets** [comment]
Ok, will do, thanks!

**Comment by Julian-B90** [comment]
Hello, you have a maintainer?

**Comment by jamesmbowler** [comment]
I'd be glad to help if you still need it.

**Comment by cuongpm1801** [comment]
Hello, this can support yii2?
