### ISSUE TITLE
'checklist'  x-editable editable column

### ISSUE THREAD

**Issue by kgoddarddev** [vitalets/x-editable-yii#95]
http://www.yiiframework.com/forum/index.php/topic/51424-gridview-chtmllistdata/page__gopid__239235#entry239235

I have the bulk of the post in the yii forum, but maybe you can help me.

I am trying to use: x-editable editable column

I have a table cost_code_group_join which phase table to cost codes using the group join table and I list the cost codes in the checklist using editable column.   I can list data, I can update data but it does not maintain what has been checked / unchecked nor does it maintain the list of those items in the column in which editable column resides.

array( 
        'class' => 'editable.EditableColumn',
        'name'  => 'cost_code_id',
        'headerHtmlOptions' => array('style' => 'width: 100px'),
        'editable' => array(
        'type' => 'checklist',  
        'model'=> $dataProvider,
        'url' => $this->createURL('UpdateCostCodeGroups',array('id'=>'phase_id')),
        'placement' => 'right',
        'source' => 'js:function() { return "'.$this->createUrl('rateNames/CostCodeSource',  
                     array('id' => (('**ID**')).'".replace("**ID**", this.getAttribute("data-pk")); }',

```
    'onSave' => 'js: function(e, params) { alert("Saved value: " + params.newValue ); console.log(params);}'
```

)),

**Comment by kgoddarddev** [comment]
I guess if there was a complete walk through for the checklist on yii cgridview editable column.

e.g. 

List data
Submit to table
Update list of checked / unchecked
Maintain text result of checked items.

**Comment by ghost** [comment]
were you able to get this ever? I've got all but the display in the table...

**Comment by kgoddarddev** [comment]
No we created a checkbox list (HTML/PHP/Jquery) and moved on.  But I would love to see this work.

**Comment by ghost** [comment]
Did the same...it's a shame, I would love to have it going too, but too
much else going on to tackle something we already worked around.

On Mon, Jun 30, 2014 at 9:43 AM, Ken Goddard notifications@github.com
wrote:

> No we created a checkbox list (HTML/PHP/Jquery) and moved on. But I would
> love to see this work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalets/x-editable-yii/issues/95#issuecomment-47539876
> .

## 

Best Regards,
Mark Meadows
www.idncommunications.com
314.649.8246
