### ISSUE TITLE
How to catch and update variables?

### ISSUE THREAD

**Issue by sachy123** [vitalets/x-editable-yii#98]
I am using the TbEditableDetailView widget as provided with the code as below

``` php
$this->widget(
    'bootstrap.widgets.TbEditableDetailView',
    array(
        'data' => $loggedinUserModel,
       'url' => $this->createUrl('Profile/UpdateRecords'),
        'attributes' => array(
            'Fname', 'Lname', 'Email',
        )
    )
);
```

How do I update the record shown in the database? I know there is something like code below, but it doesnot update the database! Please help !

``` php
public function actionUpdateRecords()
        {
                $es = new EditableSaver('User');
       $es->update();

        }
```

**Comment by Julian-B90** [comment]
How's the technical characteristic of your model? (loggedinUserModel)

**Comment by Julian-B90** [comment]
I think it is the model.
Pls show us your code
